apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-fyc-staging
resources:
  - ../../base
  - namespace.yaml
images:
  - name: demo-fyc-api
    newName: ghcr.io/rchrdkvcs/demo-fyc-api
    newTag: 4.2
patches:
  - path: replicas.yaml
