apiVersion: v1
kind: Service
metadata:
  name: demo-fyc-api
  namespace: demo-fyc
  annotations: {}
spec:
  type: LoadBalancer
  selector:
    app: demo-fyc-api
  ports:
    - name: http
      port: 80
      targetPort: http
