fatal: ambiguous argument ':.github/workflows/create-course-tags.yml': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
